const translations = {
  en: {
    "page-title": "MASTER - Applied Meteorology to Regional Weather Systems",
    "menu-produtos": "Numerical Products",
    "submenu-modelos-globais": "Global Models",
    "submenu-modelos-regionais": "Regional Models",
    "submenu-exposicao-sol": "Sun Exposure",
    "submenu-queimadas": "Burns",
    "submenu-comparacao-modelos": "Model Comparison",
    "menu-dados": "Observed Data",
    "submenu-imagens-satelite": "Satellite Images",
    "submenu-radiossondagem": "Radiosonde",
    "submenu-inmet": "INMET - Automatic Stations",
    "submenu-metar": "METAR - Airports",
    "submenu-synop": "SYNOP",
    "menu-laboratorio": "Laboratory",
    "submenu-equipe": "Team",
    "submenu-ensino": "Teaching",
    "submenu-projeto-lba": "LBA Project",
    "submenu-artigos": "Articles",
    "submenu-historico": "History",
    "submenu-solicitar-dados": "Request Data",
    "submenu-fale-conosco": "Contact Us",
    "attention-title": "ATTENTION",
    "attention-text":
      "The meteorological information on this site is automatically generated without quality control carried out visually by a meteorologist. The products are intended for education, research, training, and general dissemination. We are NOT responsible for the use of this information!",

    "footer-title":
      "<b>MASTER</b> | Applied Meteorology to Regional Weather Systems<br /><span>Institute of Astronomy, Geophysics and Atmospheric Sciences<br />University of São Paulo</span>",
    "footer-link-mapa": "Site Map",
    "footer-link-solicitar-dados": "Request Data",
    "footer-link-fale-conosco": "Contact Us",
  },
  es: {
    "page-title":
      "MASTER - Meteorología Aplicada a Sistemas Meteorológicos Regionales",
    "menu-produtos": "Productos Numéricos",
    "submenu-modelos-globais": "Modelos Globales",
    "submenu-modelos-regionais": "Modelos Regionales",
    "submenu-exposicao-sol": "Exposición al Sol",
    "submenu-queimadas": "Quemaduras",
    "submenu-comparacao-modelos": "Comparación de Modelos",
    "menu-dados": "Datos Observados",
    "submenu-imagens-satelite": "Imágenes de Satélite",
    "submenu-radiossondagem": "Radiosondeo",
    "submenu-inmet": "INMET - Estaciones Automáticas",
    "submenu-metar": "METAR - Aeropuertos",
    "submenu-synop": "SYNOP",
    "menu-laboratorio": "Laboratorio",
    "submenu-equipe": "Equipo",
    "submenu-ensino": "Enseñanza",
    "submenu-projeto-lba": "Proyecto LBA",
    "submenu-artigos": "Artículos",
    "submenu-historico": "Historia",
    "submenu-solicitar-dados": "Solicitar Datos",
    "submenu-fale-conosco": "Contáctenos",
    "attention-title": "ATENCIÓN",
    "attention-text":
      "La información meteorológica en este sitio se genera automáticamente sin control de calidad realizado visualmente por un meteorólogo. Los productos están destinados a la educación, la investigación, la capacitación y la difusión general. ¡NO nos responsabilizamos por el uso de esta información!",

    "footer-title":
      "<b>MASTER</b> | Meteorología Aplicada a Sistemas Meteorológicos Regionales<br /><span>Instituto de Astronomía, Geofísica y Ciencias Atmosféricas<br />Universidad de São Paulo</span>",
    "footer-link-mapa": "Mapa del Sitio",
    "footer-link-solicitar-dados": "Solicitar Datos",
    "footer-link-fale-conosco": "Contáctenos",
  },
  pt: {
    "page-title":
      "MASTER - Meteorologia Aplicada a Sistemas de Tempo Regionais",
    "menu-produtos": "Produtos Numéricos",
    "submenu-modelos-globais": "Modelos Globais",
    "submenu-modelos-regionais": "Modelos Regionais",
    "submenu-exposicao-sol": "Exposição ao Sol",
    "submenu-queimadas": "Queimadas",
    "submenu-comparacao-modelos": "Comparação entre Modelos",
    "menu-dados": "Dados Observados",
    "submenu-imagens-satelite": "Imagens de Satélite",
    "submenu-radiossondagem": "Radiossondagem",
    "submenu-inmet": "INMET - Estações Automáticas",
    "submenu-metar": "METAR - Aeroportos",
    "submenu-synop": "SYNOP",
    "menu-laboratorio": "Laboratório",
    "submenu-equipe": "Equipe",
    "submenu-ensino": "Ensino",
    "submenu-projeto-lba": "Projeto LBA",
    "submenu-artigos": "Artigos",
    "submenu-historico": "Histórico",
    "submenu-solicitar-dados": "Solicitar Dados",
    "submenu-fale-conosco": "Fale Conosco",
    "attention-title": "ATENÇÃO",
    "attention-text":
      "As informações meteorológicas contidas neste site são geradas de maneira automática sem controle de qualidade realizado visualmente por um meteorologista. Os produtos têm finalidade de ensino, pesquisa, treinamento e divulgação geral. NÃO nos responsabilizamos pela utilização destas informações!",

    "footer-title":
      "<b>MASTER</b> | Meteorologia Aplicada a Sistemas de Tempo Regionais<br /><span>Instituto de Astronomia, Geofísica e Ciências Atmosféricas<br />Universidade de São Paulo</span>",
    "footer-link-mapa": "Mapa do site",
    "footer-link-solicitar-dados": "Solicitar dados",
    "footer-link-fale-conosco": "Fale conosco",
  },
  en_2: {
    "page-title": "MASTER - Applied Meteorology to Regional Weather Systems",
    "menu-produtos": "Numerical Products",
    "submenu-modelos-globais": "Global Models",
    "submenu-modelos-regionais": "Regional Models",
    "submenu-exposicao-sol": "Sun Exposure",
    "submenu-queimadas": "Burns",
    "submenu-comparacao-modelos": "Model Comparison",
    "menu-dados": "Observed Data",
    "submenu-imagens-satelite": "Satellite Images",
    "submenu-radiossondagem": "Radiosonde",
    "submenu-inmet": "INMET - Automatic Stations",
    "submenu-metar": "METAR - Airports",
    "submenu-synop": "SYNOP",
    "menu-laboratorio": "Laboratory",
    "submenu-equipe": "Team",
    "submenu-ensino": "Teaching",
    "submenu-projeto-lba": "LBA Project",
    "submenu-artigos": "Articles",
    "submenu-historico": "History",
    "submenu-solicitar-dados": "Request Data",
    "submenu-fale-conosco": "Contact Us",
    "historico-title": "Laboratory History",
    "historico-content":
      "&emsp;&emsp;Since its creation in 1994, the Laboratory of Applied Meteorology to Regional Weather Systems - MASTER - has sought to contribute to the training of undergraduate and graduate students at IAG-USP in the areas of Operational Meteorology and Numerical Modeling of the Atmosphere. Initially located in the basement of the Main Building of IAG-USP, the laboratory had personal computers and servers from various companies, such as IBM, Silicon Graphics, and Sun. Most of the machines were based on 64-bit technology, something advanced for the time, and used the UNIX operating system, allowing the processing of remote sensing products, such as satellites, and the evaluation of products generated by numerical models from various centers, such as the NCEP from the United States, the ECMWF from the United Kingdom, and the CPTEC-INPE from Brazil. Over the years, due to technological advancement and important partnerships with national and foreign institutions, MASTER also started, within its operational environment, integrations with the mesoscale model “Regional Atmospheric Modeling System” - RAMS.<br><br>&emsp;&emsp;In addition to numerical model products, since its creation, MASTER has performed an extremely important activity: the storage of various routine products used in weather forecasting, such as soundings, satellite images, METAR, SYNOP, and surface stations; being a national reference in providing data or information for various types of users, from educational and research institutions to individuals interested in leisure activities.<br><br>&emsp;&emsp;MASTER innovated, in Brazil and South America, the concept of a laboratory supporting teaching and research in Meteorology. The various graduate students who passed through there and later returned to institutions across the country, used the structure and operation of MASTER as a model to set up similar laboratories in their institutions. Today, MASTER still leads innovative activities of this type of laboratory and is among the best in the world in its genre - support for teaching and research in Meteorology.<br><br>&emsp;&emsp;Currently, always based on the tripod “teaching/research/service provision”, MASTER has supported research activities at IAG in projects funded by FINEP, FAPESP, CNPq, and other national (CPTEC, IPH/UFRGS) and foreign (Harvard University) institutions. The support is provided through the development of new functionalities and numerical experiments in weather and climate forecasting models, with particular emphasis on regional processes and interaction between the surface and the atmosphere and transport/transformation of pollutants. MASTER has also offered internships for undergraduate students who become familiar with common Meteorology software (GrADS, NCL, R, among others).<br><br>&emsp;&emsp;As more recent examples of services provided by MASTER, studies on the impact of intense cyclones in the region of Petrobras oil exploration platforms, analysis of climate forecasts for the Government of the State of Bahia, numerical forecasts of wind and waves for Angra dos Reis (Petrobras) can be mentioned. A technical cooperation with the company SOMAR is also maintained on topics related to numerical weather forecasting products. MASTER also provides services for research projects at IAG/USP (FINEP, FAPESP, CNPq projects). One of the main achievements at MASTER Laboratory was the development of an automated operational system for regional weather forecasting that was transferred to various national institutions (Cearense Meteorology and Water Resources Foundation - FUNCEME, Paraná Meteorological System - SIMEPAR, and federal universities such as UFRJ, FURGS, UFPA, and UFCG). Currently, it also performs operational forecasts of the concentration of some pollutants over the metropolitan region of São Paulo.",

    "footer-title":
      "<b>MASTER</b> | Applied Meteorology to Regional Weather Systems<br /><span>Institute of Astronomy, Geophysics and Atmospheric Sciences<br />University of São Paulo</span>",
    "footer-link-mapa": "Site Map",
    "footer-link-solicitar-dados": "Request Data",
    "footer-link-fale-conosco": "Contact Us",
  },
  es_2: {
    "page-title":
      "MASTER - Meteorología Aplicada a Sistemas Meteorológicos Regionales",
    "menu-produtos": "Productos Numéricos",
    "submenu-modelos-globais": "Modelos Globales",
    "submenu-modelos-regionais": "Modelos Regionales",
    "submenu-exposicao-sol": "Exposición al Sol",
    "submenu-queimadas": "Quemaduras",
    "submenu-comparacao-modelos": "Comparación de Modelos",
    "menu-dados": "Datos Observados",
    "submenu-imagens-satelite": "Imágenes de Satélite",
    "submenu-radiossondagem": "Radiosondeo",
    "submenu-inmet": "INMET - Estaciones Automáticas",
    "submenu-metar": "METAR - Aeropuertos",
    "submenu-synop": "SYNOP",
    "menu-laboratorio": "Laboratorio",
    "submenu-equipe": "Equipo",
    "submenu-ensino": "Enseñanza",
    "submenu-projeto-lba": "Proyecto LBA",
    "submenu-artigos": "Artículos",
    "submenu-historico": "Historia",
    "submenu-solicitar-dados": "Solicitar Datos",
    "submenu-fale-conosco": "Contáctenos",
    "historico-title": "Historia del Laboratorio",
    "historico-content":
      "&emsp;&emsp;Desde su creación en 1994, el Laboratorio de Meteorología Aplicada a Sistemas de Tiempo Regionales - MASTER - ha buscado contribuir a la formación de estudiantes de pregrado y posgrado en IAG-USP en las áreas de Meteorología Operacional y Modelado Numérico de la Atmósfera. Inicialmente ubicado en el sótano del Edificio Principal de IAG-USP, el laboratorio contaba con computadoras personales y servidores de diversas empresas, como IBM, Silicon Graphics y Sun. La mayoría de las máquinas se basaban en tecnología de 64 bits, algo avanzado para la época, y utilizaban el sistema operativo UNIX, lo que permitía el procesamiento de productos de teledetección, como satélites, y la evaluación de productos generados por modelos numéricos de diversos centros, como el NCEP de Estados Unidos, el ECMWF del Reino Unido y el CPTEC-INPE de Brasil. Con los años, debido al avance tecnológico y a importantes asociaciones con instituciones nacionales y extranjeras, MASTER también comenzó, dentro de su entorno operativo, integraciones con el modelo de mesoescala “Regional Atmospheric Modeling System” - RAMS.<br><br>&emsp;&emsp;Además de los productos de modelos numéricos, desde su creación, MASTER ha realizado una actividad de extrema importancia: el almacenamiento de diversos productos de uso rutinario en la actividad de pronóstico del tiempo, como sondeos, imágenes satelitales, METAR, SYNOP y estaciones de superficie; siendo una referencia nacional en la provisión de datos o información para diversos tipos de usuarios, desde instituciones educativas y de investigación hasta individuos interesados en actividades de ocio.<br><br>&emsp;&emsp;MASTER innovó, en Brasil y América del Sur, el concepto de un laboratorio de apoyo a la enseñanza y la investigación en Meteorología. Los diversos estudiantes de posgrado que pasaron por allí y luego regresaron a instituciones en todo el país, utilizaron la estructura y el funcionamiento de MASTER como modelo para montar laboratorios similares en sus instituciones. Hoy en día, MASTER aún lidera las actividades innovadoras de este tipo de laboratorio y se encuentra entre los mejores del mundo en su género - apoyo a la enseñanza y la investigación en Meteorología.<br><br>&emsp;&emsp;Actualmente, siempre basado en el trípode “enseñanza/investigación/prestación de servicios”, MASTER ha apoyado actividades de investigación en el IAG en proyectos financiados por FINEP, FAPESP, CNPq y otras instituciones nacionales (CPTEC, IPH/UFRGS) y extranjeras (Universidad de Harvard). El apoyo se brinda a través del desarrollo de nuevas funcionalidades y experimentos numéricos en modelos de pronóstico del tiempo y del clima, con especial énfasis en los procesos regionales y la interacción entre la superficie y la atmósfera y el transporte/transformación de contaminantes. MASTER también ha ofrecido pasantías para estudiantes de pregrado que se familiarizan con software común en Meteorología (GrADS, NCL, R, entre otros).<br><br>&emsp;&emsp;Como ejemplos más recientes de servicios prestados por MASTER, se pueden mencionar estudios sobre el impacto de ciclones intensos en la región de las plataformas de exploración de petróleo de Petrobras, análisis de las previsiones climáticas para el Gobierno del Estado de Bahía, previsiones numéricas de viento y olas para Angra dos Reis (Petrobras). También se mantiene una cooperación técnica con la empresa SOMAR en temas relacionados con productos numéricos de pronóstico meteorológico. MASTER también presta servicios para proyectos de investigación en el IAG/USP (proyectos FINEP, FAPESP, CNPq). Uno de los principales logros en el Laboratorio MASTER fue el desarrollo de un sistema operativo automatizado para el pronóstico del tiempo regional que fue transferido a diversas instituciones nacionales (Fundación Cearense de Meteorología y Recursos Hídricos - FUNCEME, Sistema Meteorológico de Paraná - SIMEPAR, y universidades federales como la UFRJ, FURGS, UFPA y UFCG). Actualmente, también realiza pronósticos operativos de la concentración de algunos contaminantes sobre la región metropolitana de São Paulo.",

    "footer-title":
      "<b>MASTER</b> | Meteorología Aplicada a Sistemas Meteorológicos Regionales<br /><span>Instituto de Astronomía, Geofísica y Ciencias Atmosféricas<br />Universidad de São Paulo</span>",
    "footer-link-mapa": "Mapa del Sitio",
    "footer-link-solicitar-dados": "Solicitar Datos",
    "footer-link-fale-conosco": "Contáctenos",
  },
  pt_2: {
    "page-title":
      "MASTER - Meteorologia Aplicada a Sistemas de Tempo Regionais",
    "menu-produtos": "Produtos Numéricos",
    "submenu-modelos-globais": "Modelos Globais",
    "submenu-modelos-regionais": "Modelos Regionais",
    "submenu-exposicao-sol": "Exposição ao Sol",
    "submenu-queimadas": "Queimadas",
    "submenu-comparacao-modelos": "Comparação entre Modelos",
    "menu-dados": "Dados Observados",
    "submenu-imagens-satelite": "Imagens de Satélite",
    "submenu-radiossondagem": "Radiossondagem",
    "submenu-inmet": "INMET - Estações Automáticas",
    "submenu-metar": "METAR - Aeroportos",
    "submenu-synop": "SYNOP",
    "menu-laboratorio": "Laboratório",
    "submenu-equipe": "Equipe",
    "submenu-ensino": "Ensino",
    "submenu-projeto-lba": "Projeto LBA",
    "submenu-artigos": "Artigos",
    "submenu-historico": "Histórico",
    "submenu-solicitar-dados": "Solicitar Dados",
    "submenu-fale-conosco": "Fale Conosco",
    "historico-title": "Histórico do Laboratório",
    "historico-content":
      "&emsp;&emsp;Desde sua criação, em 1994, o Laboratório de Meteorologia Aplicada a Sistemas de Tempo Regionais - MASTER - buscou contribuir para a formação dos alunos de graduação e Pós-Graduação do IAG-USP nas áreas de Meteorologia Operacional e Modelagem Numérica da Atmosfera. No início, localizado no subsolo do Prédio Principal do IAG-USP, o laboratório contava com computadores de uso pessoal e servidores de diversas empresas, tais como IBM, Silicon Graphics e Sun. A maior parte das máquinas era baseada em tecnologia 64 bits, algo avançado para a época, e usava o sistema operacional UNIX, permitindo o tratamento de produtos de sensoriamento remoto, como satélites, e a avaliação de produtos gerados por modelos numéricos de diversos centros, tais como o NCEP dos Estados Unidos, o ECMWF do Reino Unido e o CPTEC-INPE do Brasil. Com o passar dos anos, em função do avanço tecnológico e de parcerias importantes com instituições nacionais e estrangeiras, o MASTER iniciou também, dentro de seu ambiente operacional, integrações com o modelo de mesoescala “Regional Atmospheric Modeling System” - RAMS.<br><br>&emsp;&emsp;Além dos produtos de modelos numéricos, desde a sua criação, o MASTER realiza uma atividade de extrema importância: o armazenamento de diversos produtos de uso rotineiro na atividade de previsão do tempo, tais como sondagens, imagens de satélite, METAR, SYNOP e estações de superfície; sendo referência nacional no fornecimento de dados ou informações para diversos tipos de usuários, desde instituições de ensino e pesquisa até indivíduos interessados em atividades de lazer.<br><br>&emsp;&emsp;O MASTER inovou, no Brasil e na América do Sul, o conceito de laboratório de suporte ao ensino e à pesquisa em Meteorologia. Os diversos estudantes de pós-graduação que por ali passaram e depois retornaram as instituições de todo o país, usaram a estrutura e o funcionamento do MASTER como modelo para montar laboratórios semelhantes em suas instituições. Hoje o MASTER ainda lidera as atividades inovadoras desse tipo de laboratório e está entre os melhores do mundo no gênero - apoio ao ensino e à pesquisa em Meteorologia.<br><br>&emsp;&emsp;Atualmente, sempre baseado no tripé “ensino/pesquisa/prestação de serviços”, o MASTER tem apoiado atividades de pesquisa no IAG em projetos financiados pela FINEP, FAPESP, CNPq e em outras instituições nacionais (CPTEC, IPH/UFRGS) e estrangeiras (Harvard University). O apoio se dá através do desenvolvimento de novas funcionalidades e de experimentos numéricos em modelos de previsão de tempo e clima, com particular ênfase em processos regionais e interação entre a superfície e a atmosfera e transporte/transformação de poluentes. O MASTER também tem oferecido estágios para alunos de graduação que se familiarizam com “softwares” comuns em Meteorologia (GrADS, NCL, R, entre outros ).<br><br>&emsp;&emsp;Como exemplos mais recentes de prestações de serviço realizadas pelo MASTER, podem ser mencionados estudos sobre impacto de ciclones intensos na região das plataformas de exploração de petróleo da Petrobras, análise das previsões climáticas para o Governo do Estado da Bahia, previsões numéricas de vento e ondas para Angra dos Reis (Petrobras). É também mantida uma cooperação técnica com a empresa SOMAR em temas relacionados com produtos numéricos de previsão meteorológica. O MASTER também presta serviços para projetos de pesquisa no IAG/USP (projetos FINEP, FAPESP, CNPq) Uma das principais realizações no Laboratório MASTER foi o desenvolvimento de um sistema operacional automatizado para previsão de tempo regional que foi transferido para diversas instituições nacionais (Fundação Cearense de Meteorologia e Recursos Hídricos - FUNCEME, Sistema Meteorológico do Paraná - SIMEPAR, e universidades federais como a UFRJ, FURGS, UFPA e UFCG). Atualmente, também realiza previsões operacionais da concentração de alguns poluentes sobre a região metropolitana de São Paulo.",

    "footer-title":
      "<b>MASTER</b> | Meteorologia Aplicada a Sistemas de Tempo Regionais<br /><span>Instituto de Astronomia, Geofísica e Ciências Atmosféricas<br />Universidade de São Paulo</span>",
    "footer-link-mapa": "Mapa do site",
    "footer-link-solicitar-dados": "Solicitar dados",
    "footer-link-fale-conosco": "Fale conosco",
  },
  en_3: {
    "page-title": "MASTER - Applied Meteorology to Regional Weather Systems",
    "menu-produtos": "Numerical Products",
    "submenu-modelos-globais": "Global Models",
    "submenu-modelos-regionais": "Regional Models",
    "submenu-exposicao-sol": "Sun Exposure",
    "submenu-queimadas": "Burns",
    "submenu-comparacao-modelos": "Model Comparison",
    "menu-dados": "Observed Data",
    "submenu-imagens-satelite": "Satellite Images",
    "submenu-radiossondagem": "Radiosonde",
    "submenu-inmet": "INMET - Automatic Stations",
    "submenu-metar": "METAR - Airports",
    "submenu-synop": "SYNOP",
    "menu-laboratorio": "Laboratory",
    "submenu-equipe": "Team",
    "submenu-ensino": "Teaching",
    "submenu-projeto-lba": "LBA Project",
    "submenu-artigos": "Articles",
    "submenu-historico": "History",
    "submenu-solicitar-dados": "Request Data",
    "submenu-fale-conosco": "Contact Us",

    "fale-conosco-title": "Contact Us",
    "contact-form-description": "Ask a question or critique.",
    "name-label": "Name:",
    "email-label": "Email:",
    "subject-label": "Subject:",
    "message-label": "Message:",
    "captcha-label": "Type the following text:",
    "submit-button": "Send",

    "footer-title":
      "<b>MASTER</b> | Applied Meteorology to Regional Weather Systems<br /><span>Institute of Astronomy, Geophysics and Atmospheric Sciences<br />University of São Paulo</span>",
    "footer-link-mapa": "Site Map",
    "footer-link-solicitar-dados": "Request Data",
    "footer-link-fale-conosco": "Contact Us",
  },
  es_3: {
    "page-title":
      "MASTER - Meteorología Aplicada a Sistemas Meteorológicos Regionales",
    "menu-produtos": "Productos Numéricos",
    "submenu-modelos-globais": "Modelos Globales",
    "submenu-modelos-regionais": "Modelos Regionales",
    "submenu-exposicao-sol": "Exposición al Sol",
    "submenu-queimadas": "Incendios",
    "submenu-comparacao-modelos": "Comparación de Modelos",
    "menu-dados": "Datos Observados",
    "submenu-imagens-satelite": "Imágenes Satelitales",
    "submenu-radiossondagem": "Radiosonda",
    "submenu-inmet": "INMET - Estaciones Automáticas",
    "submenu-metar": "METAR - Aeropuertos",
    "submenu-synop": "SYNOP",
    "menu-laboratorio": "Laboratorio",
    "submenu-equipe": "Equipo",
    "submenu-ensino": "Enseñanza",
    "submenu-projeto-lba": "Proyecto LBA",
    "submenu-artigos": "Artículos",
    "submenu-historico": "Historia",
    "submenu-solicitar-dados": "Solicitar Datos",
    "submenu-fale-conosco": "Contáctenos",

    "fale-conosco-title": "Contáctenos",
    "contact-form-description": "Haga una pregunta o crítica.",
    "name-label": "Nombre:",
    "email-label": "Correo electrónico:",
    "subject-label": "Asunto:",
    "message-label": "Mensaje:",
    "captcha-label": "Escriba el siguiente texto:",
    "submit-button": "Enviar",

    "footer-title":
      "<b>MASTER</b> | Meteorología Aplicada a Sistemas Meteorológicos Regionales<br /><span>Instituto de Astronomía, Geofísica y Ciencias Atmosféricas<br />Universidad de São Paulo</span>",
    "footer-link-mapa": "Mapa del sitio",
    "footer-link-solicitar-dados": "Solicitar Datos",
    "footer-link-fale-conosco": "Contáctenos",
  },
  pt_3: {
    "page-title":
      "MASTER - Meteorologia Aplicada a Sistemas de Tempo Regionais",
    "menu-produtos": "Produtos Numéricos",
    "submenu-modelos-globais": "Modelos Globais",
    "submenu-modelos-regionais": "Modelos Regionais",
    "submenu-exposicao-sol": "Exposição ao Sol",
    "submenu-queimadas": "Queimadas",
    "submenu-comparacao-modelos": "Comparação entre Modelos",
    "menu-dados": "Dados Observados",
    "submenu-imagens-satelite": "Imagens de Satélite",
    "submenu-radiossondagem": "Radiossondagem",
    "submenu-inmet": "INMET - Estações Automáticas",
    "submenu-metar": "METAR - Aeroportos",
    "submenu-synop": "SYNOP",
    "menu-laboratorio": "Laboratório",
    "submenu-equipe": "Equipe",
    "submenu-ensino": "Ensino",
    "submenu-projeto-lba": "Projeto LBA",
    "submenu-artigos": "Artigos",
    "submenu-historico": "Histórico",
    "submenu-solicitar-dados": "Solicitar Dados",
    "submenu-fale-conosco": "Fale Conosco",

    "fale-conosco-title": "Fale Conosco",
    "contact-form-description": "Faça uma pergunta ou crítica.",
    "name-label": "Nome:",
    "email-label": "Email:",
    "subject-label": "Assunto:",
    "message-label": "Mensagem:",
    "captcha-label": "Digite o texto a seguir:",
    "submit-button": "Enviar",

    "footer-title":
      "<b>MASTER</b> | Meteorologia Aplicada a Sistemas de Tempo Regionais<br /><span>Instituto de Astronomia, Geofísica e Ciências Atmosféricas<br />Universidade de São Paulo</span>",
    "footer-link-mapa": "Mapa do site",
    "footer-link-solicitar-dados": "Solicitar dados",
    "footer-link-fale-conosco": "Fale conosco",
  },
  en_4: {
    "page-title": "MASTER - Applied Meteorology to Regional Weather Systems",
    "menu-produtos": "Numerical Products",
    "submenu-modelos-globais": "Global Models",
    "submenu-modelos-regionais": "Regional Models",
    "submenu-exposicao-sol": "Sun Exposure",
    "submenu-queimadas": "Burns",
    "submenu-comparacao-modelos": "Model Comparison",
    "menu-dados": "Observed Data",
    "submenu-imagens-satelite": "Satellite Images",
    "submenu-radiossondagem": "Radiosonde",
    "submenu-inmet": "INMET - Automatic Stations",
    "submenu-metar": "METAR - Airports",
    "submenu-synop": "SYNOP",
    "menu-laboratorio": "Laboratory",
    "submenu-equipe": "Team",
    "submenu-ensino": "Teaching",
    "submenu-projeto-lba": "LBA Project",
    "submenu-artigos": "Articles",
    "submenu-historico": "History",
    "submenu-solicitar-dados": "Request Data",
    "submenu-fale-conosco": "Contact Us",

    "request-data-title": "Request Data",
    "name-label": "Name:",
    "email-label": "Email:",
    "subject-label": "Subject:",
    "message-label": "Details:",
    "profession-label": "Your profession or degree:",
    "institution-label": "Your institution:",
    "state-label": "State:",
    "city-label": "City:",
    "advisor-label": "Advisor:",
    "advisor-institution-label": "Advisor's institution:",
    "advisor-state-label": "Advisor's state:",
    "city-advisor-label": "Advisor's city:",
    "captcha-label": "Enter the following text:",
    "submit-button": "Submit",

    "footer-title":
      "<b>MASTER</b> | Applied Meteorology to Regional Weather Systems<br /><span>Institute of Astronomy, Geophysics and Atmospheric Sciences<br />University of São Paulo</span>",
    "footer-link-mapa": "Site Map",
    "footer-link-solicitar-dados": "Request Data",
    "footer-link-fale-conosco": "Contact Us",
  },
  es_4: {
    "page-title":
      "MASTER - Meteorología Aplicada a Sistemas Meteorológicos Regionales",
    "menu-produtos": "Productos Numéricos",
    "submenu-modelos-globais": "Modelos Globales",
    "submenu-modelos-regionais": "Modelos Regionales",
    "submenu-exposicao-sol": "Exposición al Sol",
    "submenu-queimadas": "Incendios",
    "submenu-comparacao-modelos": "Comparación de Modelos",
    "menu-dados": "Datos Observados",
    "submenu-imagens-satelite": "Imágenes Satelitales",
    "submenu-radiossondagem": "Radiosonda",
    "submenu-inmet": "INMET - Estaciones Automáticas",
    "submenu-metar": "METAR - Aeropuertos",
    "submenu-synop": "SYNOP",
    "menu-laboratorio": "Laboratorio",
    "submenu-equipe": "Equipo",
    "submenu-ensino": "Enseñanza",
    "submenu-projeto-lba": "Proyecto LBA",
    "submenu-artigos": "Artículos",
    "submenu-historico": "Historia",
    "submenu-solicitar-dados": "Solicitar Datos",
    "submenu-fale-conosco": "Contáctenos",

    "request-data-title": "Solicitar Datos",
    "name-label": "Nombre:",
    "email-label": "Correo electrónico:",
    "subject-label": "Finalidad:",
    "message-label": "Detalles:",
    "profession-label": "Su profesión o grado:",
    "institution-label": "Su institución:",
    "state-label": "Estado:",
    "city-label": "Ciudad:",
    "advisor-label": "Asesor:",
    "advisor-institution-label": "Institución del asesor:",
    "advisor-state-label": "Estado del asesor:",
    "city-advisor-label": "Ciudad del asesor:",
    "captcha-label": "Ingrese el siguiente texto:",
    "submit-button": "Enviar",

    "footer-title":
      "<b>MASTER</b> | Meteorología Aplicada a Sistemas Meteorológicos Regionales<br /><span>Instituto de Astronomía, Geofísica y Ciencias Atmosféricas<br />Universidad de São Paulo</span>",
    "footer-link-mapa": "Mapa del sitio",
    "footer-link-solicitar-dados": "Solicitar Datos",
    "footer-link-fale-conosco": "Contáctenos",
  },
  pt_4: {
    "page-title":
      "MASTER - Meteorologia Aplicada a Sistemas de Tempo Regionais",
    "menu-produtos": "Produtos Numéricos",
    "submenu-modelos-globais": "Modelos Globais",
    "submenu-modelos-regionais": "Modelos Regionais",
    "submenu-exposicao-sol": "Exposição ao Sol",
    "submenu-queimadas": "Queimadas",
    "submenu-comparacao-modelos": "Comparação entre Modelos",
    "menu-dados": "Dados Observados",
    "submenu-imagens-satelite": "Imagens de Satélite",
    "submenu-radiossondagem": "Radiossondagem",
    "submenu-inmet": "INMET - Estações Automáticas",
    "submenu-metar": "METAR - Aeroportos",
    "submenu-synop": "SYNOP",
    "menu-laboratorio": "Laboratório",
    "submenu-equipe": "Equipe",
    "submenu-ensino": "Ensino",
    "submenu-projeto-lba": "Projeto LBA",
    "submenu-artigos": "Artigos",
    "submenu-historico": "Histórico",
    "submenu-solicitar-dados": "Solicitar Dados",
    "submenu-fale-conosco": "Fale Conosco",

    "request-data-title": "Solicitar Dados",
    "name-label": "Nome:",
    "email-label": "Email:",
    "subject-label": "Finalidade:",
    "message-label": "Detalhes:",
    "profession-label": "Sua profissão ou graduação:",
    "institution-label": "Sua instituição:",
    "state-label": "Estado:",
    "city-label": "Cidade:",
    "advisor-label": "Orientador:",
    "advisor-institution-label": "Instituição do orientador:",
    "advisor-state-label": "Estado do orientador:",
    "city-advisor-label": "Cidade do orientador:",
    "captcha-label": "Digite o texto a seguir:",
    "submit-button": "Enviar",

    "footer-title":
      "<b>MASTER</b> | Meteorologia Aplicada a Sistemas de Tempo Regionais<br /><span>Instituto de Astronomia, Geofísica e Ciências Atmosféricas<br />Universidade de São Paulo</span>",
    "footer-link-mapa": "Mapa do site",
    "footer-link-solicitar-dados": "Solicitar dados",
    "footer-link-fale-conosco": "Fale conosco",
  },
  en_5: {
    "page-title": "MASTER - Applied Meteorology to Regional Weather Systems",
    "header-title": "Observed Data",
    "satellite-image-link": "Satellite Image",
    "radiossondagem-link": "Radiosonde",
    "inmet-link": "INMET - Automatic Stations",
    "metar-link": "METAR - Airports",
    "synop-link": "SYNOP",
    "controls-link": "Controls",
    "surface-title": "Surface",
    "metar-title": "METAR - Airports",
    "metar-option1": "Wind, temperature, and dew point",
    "metar-option2": "Wind, visibility, and pressure",
    "synop-title": "SYNOP",
    "synop-option1": "Wind, dew point, and temp.",
    "synop-option2": "Wind, precipitation, and pressure",
    "inmet-title": "INMET - Automatic Stations",
    "inmet-option1": "Wind, temperature, and dew point",
    "inmet-option2": "Wind, precipitation, and radiation",
    "altitude-title": "Sounding",
    "radiossondagem-title": "Radiosonde",
    "raob-option1": "Wind and temperature",
    "raob-option2": "Wind, humidity, and pressure",
    "caption-title": "Caption",
    "wind-title": "Winds",
    "cloudiness-title": "Cloudiness",
    "cloudless-1": "cloudless",
    "cloudy-1": "cloudy",
    "obstructed-sky-1": "obstructed sky",

    "footer-title":
      "<b>MASTER</b> | Applied Meteorology to Regional Weather Systems<br /><span>Institute of Astronomy, Geophysics and Atmospheric Sciences<br />University of São Paulo</span>",
    "footer-link-mapa": "Site Map",
    "footer-link-solicitar-dados": "Request Data",
    "footer-link-fale-conosco": "Contact Us",
  },
  es_5: {
    "page-title":
      "MASTER - Meteorología Aplicada a Sistemas Meteorológicos Regionales",
    "header-title": "Datos Observados",
    "satellite-image-link": "Imagen Satelital",
    "radiossondagem-link": "Radiosonda",
    "inmet-link": "INMET - Estaciones Automáticas",
    "metar-link": "METAR - Aeropuertos",
    "synop-link": "SYNOP",
    "controls-link": "Controles",
    "surface-title": "Superficie",
    "metar-title": "METAR - Aeropuertos",
    "metar-option1": "Viento, temperatura y punto de rocío",
    "metar-option2": "Viento, visibilidad y presión",
    "synop-title": "SYNOP",
    "synop-option1": "Viento, punto de rocío y temp.",
    "synop-option2": "Viento, precipitación y presión",
    "inmet-title": "INMET - Est. Automáticas",
    "inmet-option1": "Viento, temperatura y punto de rocío",
    "inmet-option2": "Viento, precipitación y radiación",
    "altitude-title": "Sondeo",
    "radiossondagem-title": "Radiosonda",
    "raob-option1": "Viento y temperatura",
    "raob-option2": "Viento, humedad y presión",
    "caption-title": "Subtítulo",
    "wind-title": "Vientos",
    "cloudiness-title": "Nubosidad",
    "cloudless-1": "despejado",
    "cloudy-1": "nublado",
    "obstructed-sky-1": "cielo obstruido",

    "footer-title":
      "<b>MASTER</b> | Meteorología Aplicada a Sistemas Meteorológicos Regionales<br /><span>Instituto de Astronomía, Geofísica y Ciencias Atmosféricas<br />Universidad de São Paulo</span>",
    "footer-link-mapa": "Mapa del sitio",
    "footer-link-solicitar-dados": "Solicitar Datos",
    "footer-link-fale-conosco": "Contáctenos",
  },
  pt_5: {
    "page-title":
      "MASTER - Meteorologia Aplicada a Sistemas de Tempo Regionais",
    "header-title": "Dados Observados",
    "satellite-image-link": "Imagem de Satélite",
    "radiossondagem-link": "Radiossondagem",
    "inmet-link": "INMET - Estações Automáticas",
    "metar-link": "METAR - Aeroportos",
    "synop-link": "SYNOP",
    "controls-link": "Controles",
    "surface-title": "Superfície",
    "metar-title": "METAR - Aeroportos",
    "metar-option1": "Vento, temperatura e ponto de orvalho",
    "metar-option2": "Vento, visibilidade e pressão",
    "synop-title": "SYNOP",
    "synop-option1": "Vento, p. orvalho e temp.",
    "synop-option2": "Vento, precipitação e pressão",
    "inmet-title": "INMET - Est. Automáticas",
    "inmet-option1": "Vento, temperatura e ponto de orvalho",
    "inmet-option2": "Vento, precipitação e radiação",
    "altitude-title": "Sondagem",
    "radiossondagem-title": "Radiossondagem",
    "raob-option1": "Vento e temperatura",
    "raob-option2": "Vento, umidade e pressão",
    "caption-title": "Legenda",
    "wind-title": "Ventos",
    "cloudiness-title": "Nebulosidade",
    "cloudless-1": "sem nuvens",
    "cloudy-1": "nublado",
    "obstructed-sky-1": "céu obstruído",

    "footer-title":
      "<b>MASTER</b> | Meteorologia Aplicada a Sistemas de Tempo Regionais<br /><span>Instituto de Astronomia, Geofísica e Ciências Atmosféricas<br />Universidade de São Paulo</span>",
    "footer-link-mapa": "Mapa do site",
    "footer-link-solicitar-dados": "Solicitar dados",
    "footer-link-fale-conosco": "Fale conosco",
  },
};

function changeLanguage(language) {
  const elements = document.querySelectorAll("[id]");
  elements.forEach((element) => {
    const key = element.id;
    if (translations[language][key]) {
      element.innerHTML = translations[language][key];
    }
  });
}
